name: circle_translate

permissions:
  contents: write

env:
  OPML_XML_URL_REPO: ${{ vars.OPML_XML_URL_REPO || github.repository }}
  OPML_XML_URL_USE_PAGE: ${{ vars.OPML_XML_URL_USE_PAGE || 'false' }}
  OPML_XML_URL_ANCHOR: ${{ vars.OPML_XML_URL_ANCHOR || '' }}

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev

          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Translate RSS feeds
        run: |
          python my-mtranslate.py

      - name: Generate OPML
        run: |
          python opml-generate.py \
            --repo-slug "${{ env.OPML_XML_URL_REPO }}" \
            --use-github-pages "${{ env.OPML_XML_URL_USE_PAGE }}" \
            --xml-url-anchor "${{ env.OPML_XML_URL_ANCHOR }}"

      - name: Show generated files
        run: |
          ls -al
          ls -al rss/

      - name: Push changes to remote repository
        env:
          U_NAME: github-actions[bot]
          U_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ github.token }}

        run: |
          if [[ -n "$(git status --porcelain)" ]]; then

            git config --local user.name "${U_NAME}"
            git config --local user.email "${U_EMAIL}"

            echo "====== Git status ======"
            git status -s

            git add rss/*
            git add test.ini
            git add .github/workflows/circle_translate.yml
            git add README.md

            export TZ='Asia/Shanghai'

            git commit -m "Github RSS Translate Auto Builder at $(date +'%Y-%m-%d %H:%M')"

            echo "====== Git push ======"
            git push --force origin "${{ github.ref_name }}"

          else
            echo "No changes, skip push."
          fi
