name: circle_translate

permissions:
  contents: write

env:
  OPML_XML_URL_REPO: ${{ vars.OPML_XML_URL_REPO || github.repository }}
  OPML_XML_URL_USE_PAGE: ${{ vars.OPML_XML_URL_USE_PAGE || 'false' }}
  OPML_XML_URL_ANCHOR: ${{ vars.OPML_XML_URL_ANCHOR || '' }}

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 */3 * * *'

  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:

# 工作流运行由一个或多个作业组成
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Получаем репозиторий
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
          python -m pip install --upgrade pip
          pip install mtranslate
          pip install lxml
          pip install html5lib
          pip install jinja2
          pip install googletrans
          pip install googletrans==4.0.0-rc1 bs4
          pip install beautifulsoup4 pygtrans feedparser rfeed
          pip install --upgrade feedparser
          pip install requests

      - name: ls_show
        run: |
          python my-mtranslate.py
          python opml-generate.py --repo-slug "${{ env.OPML_XML_URL_REPO }}" --use-github-pages "${{ env.OPML_XML_URL_USE_PAGE }}" --xml-url-anchor "${{ env.OPML_XML_URL_ANCHOR }}"
          ls -al rss/

      - name: Push changes to remote repository
        env:
          U_NAME: github-actions[bot]
          U_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            pwd
            git config --local user.name "${U_NAME}"
            git config --local user.email "${U_EMAIL}"

            git status -s
            git add rss/*
            git add test.ini
            git add .github/workflows/circle_translate.yml
            git add README.md

            export TZ='Asia/Shanghai'

            git commit -m "Github RSS Translate Auto Builder at `date +'%Y-%m-%d %H:%M'`"

            echo "======git push===="
            git push --force origin ${{ github.ref_name }}
          else
            echo "No changes, skip push."
          fi
